"""Add fields in DependantTask

Revision ID: 09da127c02d3
Revises: 7602216f80f9
Create Date: 2025-05-27 20:41:09.059093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09da127c02d3'
down_revision: Union[str, None] = '7602216f80f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependant_tasks', sa.Column('created_in', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependant_tasks', 'created_in')
    # ### end Alembic commands ###
