"""Add Dependant table

Revision ID: 7602216f80f9
Revises: 728cd55f5c7d
Create Date: 2025-05-23 21:07:18.115599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7602216f80f9'
down_revision: Union[str, None] = '728cd55f5c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependant_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('dependant_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dependant_to_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependant_tasks_id'), 'dependant_tasks', ['id'], unique=False)
    op.drop_constraint('tasks_dependency_task_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'dependency_task_id')
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('dependency_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_dependency_task_id_fkey', 'tasks', 'tasks', ['dependency_task_id'], ['id'])
    op.drop_index(op.f('ix_dependant_tasks_id'), table_name='dependant_tasks')
    op.drop_table('dependant_tasks')
    # ### end Alembic commands ###
